language: python

python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

os:
 - "linux"

sudo: required

services:
  - docker

before_install:
- docker pull phusion/baseimage:0.9.19

script:
 - python -c "import subprocess; pid = subprocess.Popen(\"python ohp.py --verbose\", shell=True).pid; import time; time.sleep(90); import os; os.system(\"kill -9 {0}\".format(pid))"
