language: python

python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.6-dev"

os:
 - "linux"

sudo: required

services:
  - docker

before_install:
- docker pull phusion/baseimage:0.9.19

script:
 - python -c "from os import system; import threading; threading.Thread(target=system, args=(\"python ohp.py --verbose\",)).start(); import time; time.sleep(3 * 60); import sys; sys.exit(0)"