language: python

python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

os:
 - "linux"

sudo: required

services:
  - docker
  - mongodb

before_install:
- docker pull phusion/baseimage:0.9.19
- yes | apt-get install libpcap-dev libnet-dev tshark

script:
 - service docker restart
 - pip install -r requirements.txt
 - sleep 15 # wait for mongodb
 - python -c "from core.get_modules import load_all_modules; import subprocess; import os;import time; pids = [subprocess.Popen(\"python ohp.py -m {0} --verbose > {1}\".format(module_name, module_name.replace(\"/\", \"_\")), shell=True).pid for module_name in load_all_modules()];  time.sleep(90); [os.system(\"kill -9 {0}\".format(pid)) for pid in pids]; [os.system(\"\echo -e \\\"\x0a\x0a\x0a\x0a\x0a\x0a\x0a\x0a\x0a\x0a{0}\x0a\x0a\x0a\x0a\x0a\x0a\x0a\x0a\x0a\x0a\\\"; cat {1}\".format(module_name, module_name.replace(\"/\", \"_\"))) for module_name in load_all_modules()]"
