language: python

python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7-dev"

os:
 - "linux"

sudo: required

services:
  - docker
  - mongodb

before_install:
- docker pull phusion/baseimage:0.9.19
- sudo yes | sudo apt-get install libpcap-dev libnet-dev tshark

script:
 - sudo service docker restart
 - sudo docker info
 - sudo pip install -r requirements.txt
 - sleep 15 # wait for mongodb
 - sudo python ohp.py -m all --test
