version: '3'

services:
  app:
    build: .
    command: python3 ohp.py --start-api-server
    environment:
      - FLASK_ENV=development
      - DOCKER_ENV=1
    ports:
      -  5000:5000
    volumes:
        - .:/OWASP-Honeypot
    links:
        - mongodb
    depends_on:
        - mongodb

  modules:
    build: .
    command: python3 ohp.py -m all --test
    environment:
      - DOCKER_ENV=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/OWASP-Honeypot
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 8080:80
      - 8081:81

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
    volumes:
        - ./data/db:/data/db
    expose:
        - 27017
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null # --quiet