version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

  ohp:
    build:
      context: .
      dockerfile: "Dockerfile.api"
    command: bash -c "sleep 15 && python3 ohp.py --start-api-server"
    environment:
      - FLASK_ENV=development
      - DOCKER_ENV=true
    ports:
      -  5000:5000
    volumes:
        - .:/OWASP-Honeypot
    links:
        - mongodb
    depends_on:
        - mongodb
